const data = {
      products: [
    {
      name: 'shirt 1',
      slug: 'shirt 1',
      category: 'Shirts',
      image: '/images/image1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Shirt 2',
      slug: 'shirt 2',
      category: 'Shirts',
      image: '/images/image2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'shirt 3',
      slug: 'shirt 3',
      category: 'Pants',
      image: '/images/image3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Pant 4',
      slug: 'pant 4',
      category: 'Pants',
      image: '/images/image4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
        name: 'Pant 5',
        slug: 'pant 5',
        category: 'Pants',
        image: '/images/image5.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      }  
],
};
export default data;